
const FETCH_WIKI_IMAGES_START = 'FETCH_WIKI_IMAGES_START';
const FETCH_WIKI_IMAGES_SUCCESS = 'FETCH_WIKI_IMAGES_SUCCESS';
const FETCH_WIKI_IMAGES_ERROR = 'FETCH_WIKI_IMAGES_ERROR';
const MERGE_WIKI_IMAGES_SUCCESS = 'MERGE_WIKI_IMAGES_SUCCESS';
const CLEAR_IMAGES = 'CLEAR_IMAGES';

const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
const MERGE_MOVIES_SUCCESS = 'MERGE_MOVIES_SUCCESS';
const CLEAR_MOVIES = 'CLEAR_MOVIES';

const ADD_FAVOURITE = 'ADD_FAVOURITE';
const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';

export {
  FETCH_WIKI_IMAGES_START,
  FETCH_WIKI_IMAGES_SUCCESS,
  FETCH_WIKI_IMAGES_ERROR,
  MERGE_WIKI_IMAGES_SUCCESS,
  CLEAR_IMAGES,

  FETCH_MOVIES_START,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_ERROR,
  MERGE_MOVIES_SUCCESS,
  CLEAR_MOVIES,

  ADD_FAVOURITE,
  REMOVE_FAVOURITE,
};
